name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and Test
        run: ./gradlew build
      - id: import_gpg_key
        name: Import GPG key
        uses: rnett/import-gpg-key@v0.2
        with:
          secret-key: ${{ secrets.GPG_SECRET_KEY }}
      - name: Commit index.js
        uses: EndBug/add-and-commit@v7
        with:
          add: 'dist'
          message: 'Commit new dist/'

